Create Rails App
wolox-training/cq-rails pull request #1
Opened 2018-09-14 18:33 UTC by cquiro

## Summary
Create rails app as per Trello card instructions.

##Trello Card
https://trello.com/c/t9WoR7TR/16-crear-aplicaci%C3%B3n-rails-wbooksapi

2018-09-14 18:57 UTC, facucompe approved these changes

2018-09-17 14:30 UTC, lmasello requested changes
Charly, some small changes and then it's ready to go :+1:

2018-09-17 14:30 UTC, lmasello commented on config/initializers/application_controller_renderer.rb
> +# Be sure to restart your server when you modify this file.
We can delete this file since we don't use it, right?

2018-09-17 14:30 UTC, lmasello commented on config/initializers/backtrace_silencers.rb
> +# Be sure to restart your server when you modify this file.
This file too and all others unused files.

2018-09-17 14:30 UTC, lmasello commented on config/initializers/content_security_policy.rb
> +# Be sure to restart your server when you modify this file.
As we do not have security policies in this project, we can delete this.

2018-09-17 14:30 UTC, lmasello commented on config/locales/en.yml
> +# Files in the config/locales directory are used for internationalization
Remove these comments.

2018-09-17 14:30 UTC, lmasello commented on config/storage.yml
> +# Remember not to checkin your GCS keyfile to a repository
Remove these comments.

2018-09-20 13:27 UTC, lmasello approved these changes

2018-09-20 13:30 UTC, merged