Send New Rent Email
wolox-training/cq-rails pull request #13
Opened 2018-09-28 18:51 UTC by cquiro

## Summary

- Add sidekiq to Gemfile and bundle install
- Set action_job.queue_adapter to sidekiq
- Set action_mailer.delivary method to :smtp and set configuration to use mailtrap
- Add mailtrap credentials to config/credentials.yml.enc
- Create RentsMailer
- Add slim-rails to Gemfile and bundle install
- Write html email
- Call RentsMailer.send_new_rent_email from the create action of the rents_controller

## Trello Card

https://trello.com/c/JdlxdT35/11-mandar-email-al-usuario-cuando-se-crea-un-rent

2018-09-28 19:48 UTC, facucompe requested changes
Just those small things

2018-09-28 19:48 UTC, facucompe commented on config/environments/production.rb
> +    :user_name => Rails.application.credentials.mailtrap[:username],
You can use new sintax

2018-09-28 19:48 UTC, facucompe commented on config/environments/production.rb
> +    :address => 'smtp.mailtrap.io',
I would add this to the env variables

2018-10-01 18:50 UTC, facucompe approved these changes

2018-10-02 19:02 UTC, lmasello approved these changes
Well done!

2018-10-02 19:02 UTC, lmasello commented on app/mailers/application_mailer.rb
> +  default from: 'info@wbooks.com'
There is no need to change it, but just for your information, this is preferable to be taken from an environment variable :)

2018-10-02 19:34 UTC, merged