Book Suggestions Endpoint Specs
wolox-training/cq-rails pull request #19
Opened 2018-10-02 14:06 UTC by cquiro

## Summary

Add specs for BookSuggestions#create.

## Trello Card

https://trello.com/c/C36Bow4G/30-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

2018-10-02 17:00 UTC, facucompe requested changes
I know the card have this tests, but we should add more for the failing cases

2018-10-02 17:00 UTC, facucompe commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        request.headers['HTTP_ACCESS_TOKEN'] = nil
Instead of this include `Authenticated User` in the logged user context

2018-10-03 19:41 UTC, facucompe approved these changes

2018-10-04 14:16 UTC, lmasello approved these changes

2018-10-04 19:49 UTC, merged