Create Book Model
wolox-training/cq-rails pull request #6
Opened 2018-09-21 15:28 UTC by cquiro

## Summary
- Generate Book model as per Trello Card specs.
- Run migrations.
- Add validations to book model (presence: true for all attributes).

## Trello Card
https://trello.com/c/trftJgf4/20-crear-modelo-de-book

2018-09-24 13:39 UTC, lmasello requested changes
Just a small fix

2018-09-24 13:39 UTC, lmasello commented on db/schema.rb
> +    t.string "provider", default: "email", null: false
Be careful with this... The migration of the previous PR is affecting this one. To avoid this, reset the db with `rails db:drop db:create db:migrate`

2018-09-24 15:16 UTC, facucompe approved these changes

2018-09-25 14:56 UTC, lmasello approved these changes

2018-09-25 14:57 UTC, merged