Show Index Books
wolox-training/cq-rails pull request #9
Opened 2018-09-25 14:48 UTC by cquiro

## Summary

* Add and configure gems versionist, active_model_serializers and wor-paginate
* Create endpoint for books#show
* Create endpoint for books#index (including pagination)
* Require authentication for all actions except the ones that are performed by the devise_controller

## Trello Card

https://trello.com/c/K1gUlUqv/23-crear-rutas-index-y-show-para-book

2018-09-25 16:19 UTC, facucompe requested changes

2018-09-25 16:19 UTC, facucompe commented on app/serializers/api/v1/book_serializer.rb
> +module Api
No need to use `api/v1` folders

2018-09-25 16:19 UTC, facucompe commented on app/controllers/api/v1/books_controller.rb
> +      include Wor::Paginate
Move this to application controller

2018-09-25 16:19 UTC, facucompe commented on app/controllers/api/v1/books_controller.rb
> +        @book ||= Book.find(params[:id])
No need to use instance variable or memoization.

2018-09-25 16:19 UTC, facucompe commented on app/controllers/api/v1/books_controller.rb
> +        @book ||= Book.find(params[:id])
Also use a separate method to permit params.
```
def book_params
  params.permit(:id)
end
```

2018-09-25 16:19 UTC, facucompe commented on app/controllers/api/v1/books_controller.rb
> +        @books ||= Book.all
Same here. No need to use an instance variable and memoization

2018-09-25 16:19 UTC, facucompe commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, unless: :devise_controller?
We usually use an `api_controller` that inherits from `application_controller` where we put the authentication.

2018-09-25 16:28 UTC, facucompe commented
Try using **spinal-case** for branch names instead of **snake_case**

2018-09-25 19:11 UTC, lmasello approved these changes
Just what facu asked and then it's good to go 👍

2018-09-25 20:24 UTC, facucompe requested changes

2018-09-25 20:24 UTC, facucompe commented on app/controllers/api/v1/books_controller.rb
> +        render_paginated books, each_serializer: Api::V1::BookSerializer, status: :ok
Watch out, you are not serializing. It should just be `BookSerializer`

2018-09-26 12:09 UTC, cquiro commented on app/controllers/api/v1/books_controller.rb
> +        render_paginated books, each_serializer: Api::V1::BookSerializer, status: :ok
@facucompe Done!

2018-09-26 14:54 UTC, facucompe approved these changes

2018-09-26 15:12 UTC, merged